@echo off
echo Setting up database...
cd /d "c:\Users\manis\Downloads\Next_js project-20251126T021557Z-1-001\Next_js project\SmartDrishti"
echo Generating Prisma client...
npx prisma generate
echo Pushing schema to database...
npx prisma db push --accept-data-loss
echo Testing database connection...
node -e "const { PrismaClient } = require('@prisma/client'); const prisma = new PrismaClient(); prisma.project.findMany().then(projects => console.log('Success! Found ' + projects.length + ' projects')).catch(err => console.error('Error:', err.message));"
echo Database setup complete!
pause